name: Deploy with Docker and Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:


#stage-1
jobs:
  deploy:
    runs-on: self-hosted

# # Login to aws account
#     env:
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#       ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       # Step 1: Configure AWS credentials
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

# #stage-2
#   test:
#     runs-on: ubuntu-latest
#     needs: deploy
    
#     steps:
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       # Step 2: Build Docker Image
#       - name: Build Docker Image
#         run: docker build -t my-app-image:2 .

#       - name: Check Docker Images
#         run: docker images -a 
